title: Digitalsquid
email: hello@digitalsquid.co.uk
description: A collection of projects by Will Shackleton
url: "https://www.digitalsquid.co.uk"
twitter_username: wshackleton
github_username: w-shackleton

markdown: kramdown
